### ISSUE TITLE
v2.0.0 fail to install with npm

### ISSUE THREAD

**Issue by KamyarTaher** [starknet-community-libs/get-starknet#168]
Hello,
I tried to install the last release, and whatever I do I get the following error.  1.5.0 works fine.

> npm ERR! code ETARGET
> npm ERR! notarget No matching version found for get-starknet-core@^2.0.0.
> npm ERR! notarget In most cases you or one of your dependencies are requesting
> npm ERR! notarget a package version that doesn't exist.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2022-12-08T15_06_46_813Z-debug-0.log

**Comment by KamyarTaher** [comment]
Here is the complete log of the issue.

> 
> 0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
> 1 info using npm@8.5.5
> 2 info using node@v17.9.0
> 3 timing npm:load:whichnode Completed in 0ms
> 4 timing config:load:defaults Completed in 1ms
> 5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 0ms
> 6 timing config:load:builtin Completed in 0ms
> 7 timing config:load:cli Completed in 2ms
> 8 timing config:load:env Completed in 0ms
> 9 timing config:load:file:/root/metacube/client/.npmrc Completed in 1ms
> 10 timing config:load:project Completed in 8ms
> 11 timing config:load:file:/root/.npmrc Completed in 0ms
> 12 timing config:load:user Completed in 0ms
> 13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
> 14 timing config:load:global Completed in 0ms
> 15 timing config:load:validate Completed in 1ms
> 16 timing config:load:credentials Completed in 1ms
> 17 timing config:load:setEnvs Completed in 0ms
> 18 timing config:load Completed in 15ms
> 19 timing npm:load:configload Completed in 15ms
> 20 timing npm:load:setTitle Completed in 0ms
> 21 timing config:load:flatten Completed in 3ms
> 22 timing npm:load:display Completed in 5ms
> 23 verbose logfile /root/.npm/_logs/2022-12-08T15_06_46_813Z-debug-0.log
> 24 timing npm:load:logFile Completed in 5ms
> 25 timing npm:load:timers Completed in 0ms
> 26 timing npm:load:configScope Completed in 0ms
> 27 timing npm:load Completed in 26ms
> 28 timing arborist:ctor Completed in 1ms
> 29 silly logfile start cleaning logs, removing 1 files
> 30 timing idealTree:init Completed in 840ms
> 31 timing idealTree:userRequests Completed in 0ms
> 32 silly idealTree buildDeps
> 33 silly fetch manifest get-starknet@^2.0.0
> 34 verbose shrinkwrap failed to load node_modules/.package-lock.json out of date, updated: node_modules
> 35 http fetch GET 200 https://registry.npmjs.org/get-starknet 175ms (cache hit)
> 36 silly placeDep ROOT get-starknet@2.0.0 REPLACE for: my-app@0.1.0 want: ^2.0.0
> 37 silly fetch manifest get-starknet-core@^2.0.0
> 38 http fetch GET 200 https://registry.npmjs.org/get-starknet-core 791ms (cache hit)
> 39 timing idealTree:#root Completed in 985ms
> 40 silly placeDep node_modules/get-starknet get-starknet-core@ OK for: get-starknet@2.0.0 want: ^2.0.0
> 41 timing idealTree:node_modules/get-starknet Completed in 1ms
> 42 timing idealTree:node_modules/get-starknet/node_modules/get-starknet-core Completed in 0ms
> 43 timing idealTree:buildDeps Completed in 988ms
> 44 timing idealTree:fixDepFlags Completed in 10ms
> 45 timing idealTree Completed in 1840ms
> 46 timing command:install Completed in 1855ms
> 47 verbose type range
> 48 verbose stack get-starknet-core: No matching version found for get-starknet-core@^2.0.0.
> 48 verbose stack     at module.exports (/usr/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
> 48 verbose stack     at /usr/lib/node_modules/npm/node_modules/pacote/lib/registry.js:126:26
> 48 verbose stack     at async Promise.all (index 0)
> 48 verbose stack     at async Arborist.[buildDepStep] (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1066:5)
> 48 verbose stack     at async Arborist.buildIdealTree (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
> 48 verbose stack     at async Promise.all (index 1)
> 48 verbose stack     at async Arborist.reify (/usr/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:153:5)
> 48 verbose stack     at async Install.exec (/usr/lib/node_modules/npm/lib/commands/install.js:159:5)
> 48 verbose stack     at async module.exports (/usr/lib/node_modules/npm/lib/cli.js:66:5)
> 49 verbose cwd /root/metacube/client
> 50 verbose Linux 5.4.0-125-generic
> 51 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
> 52 verbose node v17.9.0
> 53 verbose npm  v8.5.5
> 54 error code ETARGET
> 55 error notarget No matching version found for get-starknet-core@^2.0.0.
> 56 error notarget In most cases you or one of your dependencies are requesting
> 56 error notarget a package version that doesn't exist.
> 57 verbose exit 1
> 58 timing npm Completed in 2048ms
> 59 verbose unfinished npm timer reify 1670512007004
> 60 verbose unfinished npm timer reify:loadTrees 1670512007016
> 61 verbose code 1
> 62 error A complete log of this run can be found in:
> 62 error     /root/.npm/_logs/2022-12-08T15_06_46_813Z-debug-0.log
>
